query CartLinesDiscountsGenerateRunInput {
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          product {
            id
            productType
          }
        }
      }
    }
    buyerIdentity {
      customer {
        id
        tags
      }
    }
  }
  enteredDiscountCodes {
    code
    rejectable
  }
  discount {
    metafield(namespace: "$app", key: "function-configuration") {
      value
    }
  }
}
