query CartLinesDiscountsGenerateRunInput {
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          product {
            id
            collections(first: 10) {
              nodes {
                id
              }
            }
          }
        }
      }
    }
  }
  discount {
    metafield(namespace: "$app", key: "function-configuration") {
      value
    }
  }
}
